# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linux_gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(670, 589)
        self.label_info_command = QtWidgets.QLabel(Form)
        self.label_info_command.setGeometry(QtCore.QRect(10, 10, 111, 17))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_info_command.setFont(font)
        self.label_info_command.setObjectName("label_info_command")
        self.copybutton = QtWidgets.QPushButton(Form)
        self.copybutton.setGeometry(QtCore.QRect(120, 10, 91, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.copybutton.setFont(font)
        self.copybutton.setObjectName("copybutton")
        self.auto_get_check = QtWidgets.QCheckBox(Form)
        self.auto_get_check.setGeometry(QtCore.QRect(380, 10, 111, 17))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.auto_get_check.setFont(font)
        self.auto_get_check.setObjectName("auto_get_check")
        self.not_auto_get_check = QtWidgets.QCheckBox(Form)
        self.not_auto_get_check.setGeometry(QtCore.QRect(510, 10, 101, 17))
        self.not_auto_get_check.setObjectName("not_auto_get_check")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(492, 34, 113, 20))
        self.lineEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit.setObjectName("lineEdit")
        self.centos6radio = QtWidgets.QRadioButton(Form)
        self.centos6radio.setGeometry(QtCore.QRect(80, 40, 82, 17))
        self.centos6radio.setObjectName("centos6radio")
        self.centos7radio = QtWidgets.QRadioButton(Form)
        self.centos7radio.setGeometry(QtCore.QRect(170, 40, 82, 17))
        self.centos7radio.setObjectName("centos7radio")
        self.ubunturadio = QtWidgets.QRadioButton(Form)
        self.ubunturadio.setGeometry(QtCore.QRect(290, 40, 101, 17))
        self.ubunturadio.setObjectName("ubunturadio")
        self.debianradio = QtWidgets.QRadioButton(Form)
        self.debianradio.setGeometry(QtCore.QRect(380, 40, 82, 17))
        self.debianradio.setObjectName("debianradio")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 641, 521))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_info_command.setBuddy(self.textEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_info_command.setText(_translate("Form", "Linux 命令生成"))
        self.copybutton.setText(_translate("Form", "复制到粘贴板"))
        self.auto_get_check.setText(_translate("Form", "自动获取网卡名"))
        self.not_auto_get_check.setText(_translate("Form", "输入网卡名"))
        self.centos6radio.setText(_translate("Form", "CentOS 6"))
        self.centos7radio.setText(_translate("Form", "CentOS 7"))
        self.ubunturadio.setText(_translate("Form", "Ubuntu"))
        self.debianradio.setText(_translate("Form", "Debian"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'vt100\';\"><br /></p></body></html>"))
