# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'route_gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 537)
        self.routeText = QtWidgets.QTextEdit(Form)
        self.routeText.setGeometry(QtCore.QRect(20, 110, 471, 401))
        self.routeText.setObjectName("routeText")
        self.generateButton = QtWidgets.QPushButton(Form)
        self.generateButton.setGeometry(QtCore.QRect(90, 20, 111, 31))
        self.generateButton.setObjectName("generateButton")
        self.copyButton = QtWidgets.QPushButton(Form)
        self.copyButton.setGeometry(QtCore.QRect(180, 60, 111, 31))
        self.copyButton.setObjectName("copyButton")
        self.gatewayRadio = QtWidgets.QRadioButton(Form)
        self.gatewayRadio.setGeometry(QtCore.QRect(234, 19, 81, 21))
        self.gatewayRadio.setObjectName("gatewayRadio")
        self.staticRadio = QtWidgets.QRadioButton(Form)
        self.staticRadio.setGeometry(QtCore.QRect(307, 19, 91, 21))
        self.staticRadio.setObjectName("staticRadio")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(382, 23, 54, 12))
        self.label.setObjectName("label")
        self.VLANLine = QtWidgets.QLineEdit(Form)
        self.VLANLine.setGeometry(QtCore.QRect(416, 19, 113, 20))
        self.VLANLine.setObjectName("VLANLine")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(538, 22, 31, 16))
        self.label_2.setObjectName("label_2")
        self.clientLine = QtWidgets.QLineEdit(Form)
        self.clientLine.setGeometry(QtCore.QRect(570, 20, 113, 20))
        self.clientLine.setObjectName("clientLine")
        self.clientText = QtWidgets.QTextEdit(Form)
        self.clientText.setGeometry(QtCore.QRect(520, 109, 291, 411))
        self.clientText.setObjectName("clientText")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(492, 42, 16, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.copyButton_2 = QtWidgets.QPushButton(Form)
        self.copyButton_2.setGeometry(QtCore.QRect(612, 61, 111, 31))
        self.copyButton_2.setObjectName("copyButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.generateButton.setText(_translate("Form", "生成"))
        self.copyButton.setText(_translate("Form", "复制下列文本"))
        self.gatewayRadio.setText(_translate("Form", "网关配置"))
        self.staticRadio.setText(_translate("Form", "静态路由"))
        self.label.setText(_translate("Form", "VLAN:"))
        self.label_2.setText(_translate("Form", "客户:"))
        self.copyButton_2.setText(_translate("Form", "复制下列文本"))
