# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'switch_gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(437, 368)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(130, 10, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.ser_num_one = QtWidgets.QLineEdit(Form)
        self.ser_num_one.setGeometry(QtCore.QRect(20, 90, 161, 31))
        self.ser_num_one.setObjectName("ser_num_one")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(13, 60, 191, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 191, 21))
        self.label_3.setObjectName("label_3")
        self.ser_num_two = QtWidgets.QLineEdit(Form)
        self.ser_num_two.setGeometry(QtCore.QRect(20, 300, 161, 31))
        self.ser_num_two.setObjectName("ser_num_two")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(240, 80, 181, 251))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "转移IP"))
        self.label.setText(_translate("Form", "输入需要转移走IP的机器编号"))
        self.label_3.setText(_translate("Form", "输入要添加转移IP的机器编号"))
