# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_gg(object):
    def setupUi(self, win_gg):
        win_gg.setObjectName("win_gg")
        win_gg.resize(669, 596)
        self.label = QtWidgets.QLabel(win_gg)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 31))
        self.label.setObjectName("label")
        self.encheck = QtWidgets.QCheckBox(win_gg)
        self.encheck.setGeometry(QtCore.QRect(160, 36, 101, 21))
        self.encheck.setObjectName("encheck")
        self.win8radio = QtWidgets.QRadioButton(win_gg)
        self.win8radio.setGeometry(QtCore.QRect(240, 39, 89, 16))
        self.win8radio.setObjectName("win8radio")
        self.win12radio = QtWidgets.QRadioButton(win_gg)
        self.win12radio.setGeometry(QtCore.QRect(330, 38, 89, 16))
        self.win12radio.setObjectName("win12radio")
        self.interline = QtWidgets.QLineEdit(win_gg)
        self.interline.setGeometry(QtCore.QRect(429, 34, 131, 21))
        self.interline.setObjectName("interline")
        self.textEdit = QtWidgets.QTextEdit(win_gg)
        self.textEdit.setGeometry(QtCore.QRect(13, 60, 641, 521))
        self.textEdit.setObjectName("textEdit")
        self.copybutton = QtWidgets.QPushButton(win_gg)
        self.copybutton.setGeometry(QtCore.QRect(112, 6, 91, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.copybutton.setFont(font)
        self.copybutton.setObjectName("copybutton")

        self.retranslateUi(win_gg)
        QtCore.QMetaObject.connectSlotsByName(win_gg)

    def retranslateUi(self, win_gg):
        _translate = QtCore.QCoreApplication.translate
        win_gg.setWindowTitle(_translate("win_gg", "Form"))
        self.label.setText(_translate("win_gg", "Windows 命令生成"))
        self.encheck.setText(_translate("win_gg", "英文版本"))
        self.win8radio.setText(_translate("win_gg", "Win2008R2"))
        self.win12radio.setText(_translate("win_gg", "Win2012R2"))
        self.copybutton.setText(_translate("win_gg", "复制到粘贴板"))
